project:
  type: website

website:
  title: "Re-Learn Lab"
  navbar:
    background: info
    left:
      - text: "Home"
        file: index.qmd
      - text: "People"
        file: people.qmd
      - text: "Projects"
        file: projects.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
