project:
  type: website

website:
  title: "Re-Learn Lab"
  sidebar:
    style: "floating"
    search: true
    contents: 
      - section: "Home"
        contents:
          - index.qmd
      - section: "Team"
        contents:
          - team.qmd
      - section: "Projects"
        contents:
          - project_shade.qmd
          - project_Attento.qmd
          - project_ADL-older.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

