project:
  type: website

website:
  title: "Re-Learn Lab"
  navbar:
    background: info
    left:
      - text: "Home"
        file: index.qmd
      - text: "People"
        file: team_0_landing_page.qmd
      - text: "Projects"
        file: project_0_landing_page.qmd
        
  
  
  sidebar:
    style: "floating"
    search: true
    contents: 
      - section: "Home"
        contents:
          - text: Re-Learn Lab
            file: index.qmd
      - section: "Team"
        contents:
          - text: People
            file: team_0_landing_page.qmd
      - section: "Projects"
        contents:
          - project_shade.qmd
          - project_attento.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
