project:
  type: website

website:
  title: "Re-Learn Lab"
  navbar:
    logo: "fig/Hedgehog_logo.jpeg"
    background: info
    left:
      - text: "Home"
        file: index.qmd
      - text: "People"
        file: people.qmd
      - text: "Projects"
        file: projects.qmd
  
  page-footer: "Copyright 2024"
  cookie-consent: true
        
format:
  html:
    theme: slate
    css: styles.css
    toc: true

editor: visual
